FROM node:22

WORKDIR /app

# สร้างโฟลเดอร์สำหรับ SQLite database
RUN mkdir -p /app/src/dbsqlite

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# ตั้งค่า environment variables
ENV NODE_ENV=development
ENV SQLITE_DATABASE_PATH=/app/src/dbsqlite/data.sqlite3
ENV APP_PORT=3003

EXPOSE 3003



CMD [ "npm", "run", "start:dev" ]

# npm run start:dev  

FROM debian:stable-slim

RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends install sqlite3=3.* && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	mkdir -p /root/src/dbsqlite/

WORKDIR /root/src/dbsqlite/
ENTRYPOINT [ "sqlite3" ]
