FROM node:22

WORKDIR /app

# สร้างโฟลเดอร์สำหรับ SQLite database
RUN mkdir -p /app/data

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# ตั้งค่า environment variables
ENV NODE_ENV=development
ENV SQLITE_DATABASE_PATH=/app/src/dbsqlite/data.sqlite3
ENV APP_PORT=3003

EXPOSE 3003

CMD [ "npm", "run", "start:dev" ]
